services:
  api:
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_LOG_LEVEL: INFO
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G

  web:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
